version: '3'

services:
    pipeline:
        build:
            context: .
            dockerfile: Dockerfile
        image: subreddit_ranking
        ports:
            - "5000:5000"
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'Abijith12@'
        ports:
            - "3307:3306"
