version: '3'

services:
    pipeline:
        build:
            context: .
            dockerfile: Dockerfile
        image: subreddit_ranking
        
    
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'Abijith12@'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'Abijith12@'
        ports:
            - "3306:3306"
